aes: vaes detection is provided by cpufeatures-0.2.12 (#514)
This fixes a compilation error when bumping to aes-0.9.0-rc.2 (which
brings a vaes backend):
```
error: no rules expected `"vaes"`
   --> $HOME/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aes-0.9.0-rc.2/src/x86.rs:38:38
    |
 38 |     cpufeatures::new!(features_vaes, "vaes");
    |                                      ^^^^^^ no rules expected this token in macro call
```