aes: remove use of `aarch64_target_feature`
It's been stabilized: rust-lang/rust#90620

Because of that, it's breaking the build on recent nightlies:

https://github.com/RustCrypto/block-ciphers/runs/7968517726?check_suite_focus=true#step:7:103

> error: the feature `aarch64_target_feature` has been stable since
> 1.61.0 and no longer requires an attribute to enable    aes: remove use of `aarch64_target_feature`

It's been stabilized: rust-lang/rust#90620

Because of that, it's breaking the build on recent nightlies:

https://github.com/RustCrypto/block-ciphers/runs/7968517726?check_suite_focus=true#step:7:103

> error: the feature `aarch64_target_feature` has been stable since
> 1.61.0 and no longer requires an attribute to enable